### ISSUE TITLE
problem running release_build.sh

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog-doc#551] opened 2018-02-11 09:37 UTC
On a clone of ```master``` I experimentally did:
```
$ tools/release_build.sh 8.33.0


#######################################################################
#                                                                     #
# Purpose: Create an official rsyslog docs release tarball            #
#                                                                     #
# Before proceeding, please confirm that you have performed the       #
# following steps:                                                    #
#                                                                     #
# 1. Manually fetched, merged and tagged the changes to the stable    #
#    branch that are intended to reflect the latest release.          #
#                                                                     #
# 2. Checkout the latest tag (or stable branch)                       #
#                                                                     #
# 3. Remove uncommitted files to help prevent them from being         #
#    included in the release tarball                                  #
#                                                                     #
# These steps can be automated, but have been left as-is for this     #
# version of the release script. If desired, a future version of      #
# the script can be enhanced to include this functionality.           #
#                                                                     #
#                                                                     #
#             PRESS ENTER TO CONTINUE OR CTRL+C TO CANCEL             #
#                                                                     #
#######################################################################


Running Sphinx v1.6.6
making output directory...

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/home/rger/.local/lib/python2.7/site-packages/sphinx/config.py", line 157, in __init__
    execfile_(filename, config)
  File "/home/rger/.local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/rger/.local/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 247, in <module>
    if release_type == 'dev':
NameError: name 'release_type' is not defined

sphinx-build failed... aborting
```

**Comment by deoren** [comment] 2018-02-11 09:42
@rgerhards Replicated. Will take a look and see if maybe a change from another branch didn't make its way to master as intended.

**Comment by deoren** [comment] 2018-02-11 10:11
The script was updated at one point to no longer use the value passed from the command-line, but instead calculate the value from the latest Git tag. This failure was a bit of a rookie mistake and involved a reference to a value that was set inside a nested if/else block outside of that block.

A quick fix here was just to add a complementary else block to set the value to something else indicative of the type of build. This will be fixed in a better way once #535 is resolved.

**Comment by rgerhards** [comment] 2018-02-11 10:26
I often need to build the release before tagging, e.g for final testing
purposes. Tag is the last thing in release process.

Sent from phone, thus brief.

**Comment by deoren** [comment] 2018-02-11 10:46
> I often need to build the release before tagging, e.g for final testing purposes. Tag is the last thing in release process.

In that case, with the current version of the script, the version number would just be off by one until the tag is created.

**Comment by deoren** [comment] 2018-02-11 11:23
The original issue that was reported should be resolved now. I'll do further work on the script as part of #535.

**Closed** 2018-02-11 11:42 UTC
Labels: bug

**Comment by rgerhards** [comment] 2018-02-11 13:23
thx -  I just verified and it works. For me I think it works sufficiently well and I can easily work-around any remaining quirks with in 1 minute or 2. So IMHO no real need to change it again.
