### ISSUE TITLE
Documentation search fails

### ISSUE THREAD

**Issue by hmg018** [rsyslog/rsyslog-doc#401] opened 2017-12-03 01:35 UTC
I was disappointed by the search facility at http://www.rsyslog.com/.
I was looking for "rsyslog.conf" but nothing came up:

------------------------------------------------------------------------
Search

From here you can search these documents. Enter your search words into
the box below and click "search". Note that the search function will
automatically search for all of the words. Pages containing fewer
words won't appear in the result list.

rsyslog.conf    /search/

Search Results

Your search did not match any documents. Please make sure that all
words are spelled correctly and that you've selected enough
categories.

------------------------------------------------------------------------
http://www.rsyslog.com/doc/master/search.html?q=rsyslog.conf

And yet exactly that text appears in 
http://www.rsyslog.com/doc/master/configuration/basic_structure.html#configuration-file:

------------------------------------------------------------------------
Configuration File

Upon startup, rsyslog reads its configuration from the rsyslog.conf
file by default. 

------------------------------------------------------------------------

**Comment by rgerhards** [comment] 2017-12-03 09:22
@ralnoc do you have an idea how this could be fixed in sphinx? If not, might it be better/possible to turn of the Sphinx-generated search as to not provide a false sense of functionality?

Any one else has a thought on this?

**Comment by deoren** [comment] 2017-12-04 15:20
> @rgerhards: Any one else has a thought on this?

Perhaps for the time being replace the existing search option with a Google site search box?

Example search result for "rsyslog.conf":

![rsyslog com_documentation_google_site_search_example_2017-12-04](https://user-images.githubusercontent.com/1550338/33560041-4289c802-d8d4-11e7-9947-a3c6ebff7354.png)

**Comment by rgerhards** [comment] 2017-12-05 08:06
@deoren The problem from my PoV is that the search box is **generated** by sphinx and I would need to find a way how to change it's behaviour. @Ralnoc intially set this up and so far I never needed to touch that area. Unfortunately, I currently have no time to dig deeper into this issues, as there are far more important ones. But maybe it's relatively straightforward to turn the box off, which would "automatically" make folks go to google ;-)

**Comment by Ralnoc** [comment] 2017-12-05 09:45
This was configured originally to build a search index off the contents of the various files. It should be automatically available as soon as it is compiled.

I proceeded to test v8-stable and master for myself, locally on my machine, just to see if there is a configuration setting amiss, and interestingly enough, my local rendered version, with no changes to any settings, searches as expected:
![image](https://user-images.githubusercontent.com/2515191/33599508-fbf375f8-d96b-11e7-9d09-7c0c27d0bdb0.png)

I'm using a Python virtual environment with the following Python modules installed:
```alabaster==0.7.10
Babel==2.5.1
certifi==2017.11.5
chardet==3.0.4
docutils==0.14
idna==2.6
imagesize==0.7.1
Jinja2==2.10
MarkupSafe==1.0
pkg-resources==0.0.0
Pygments==2.2.0
pytz==2017.3
requests==2.18.4
six==1.11.0
snowballstemmer==1.2.1
Sphinx==1.6.5
sphinxcontrib-websupport==1.0.1
typing==3.6.2
urllib3==1.22
```

I quite honestly just ran `virtualenv /path/to/virtualenv/rsyslog-doc ; . /path/to/virtualenv/rsyslog-doc/bin/activate ; sphinx-build -b html source build` on a fresh download of the repo set on `master`, and then switched to the branch `v8-stable` to run the same test. No changes to any files.

@rgerhards - Which you get a chance, can you check to find out what kind of post processing is being done of the content after it is built by sphinx-build? Also someone should verify which version of Sphinx is being used to build it and upgrading to 1.6.5 as a step in working to resolve it.

**Comment by deoren** [comment] 2017-12-05 14:06
> @rgerhards @deoren The problem from my PoV is that the search box is generated by sphinx and I would need to find a way how to change it's behaviour.

Acknowledged. I spoke in ignorance (I didn't realize sphinx created/managed search indexes, that's pretty useful) and assumed that the inner working behind the search interface were complex enough to warrant an extended period of troubleshooting. I don't blame you for wanting to focus on fixing just the root cause if it's an easy enough fix to apply.

**Comment by deoren** [comment] 2017-12-08 14:36
If fixing the Sphinx search option isn't feasible, perhaps just a Google site search box instead? If nothing else, that could be a temp fix until someone has time to do more.

**Comment by rgerhards** [comment] 2017-12-08 14:39
> If fixing the Sphinx search option isn't feasible, perhaps just a Google site search box instead? If nothing else, that could be a temp fix until someone has time to do more.

yup, but for this we need unfortunately need to know how to modify the search box. admitted, it's possibly the same thing with removing the box ;-)

**Comment by deoren** [comment] 2017-12-08 16:00
@rgerhards Sorry for the confusion re the last reply. I tried to respond by email on Dec 4, but since the response never showed up here I went ahead and made the response by the web UI instead. Evidently the email finally went through, albeit 4 days late. :|

**Comment by rgerhards** [comment] 2017-12-09 10:10
@Ralnoc sorry, overlooked that post initially ;-)

> Which you get a chance, can you check to find out what kind of post processing is being done of the content after it is built by sphinx-build? Also someone should verify which version of Sphinx is being used to build it and upgrading to 1.6.5 as a step in working to resolve it.

will check and report back

**Comment by rgerhards** [comment] 2017-12-12 18:02
@Ralnoc @deoren The doc is build on a debian jessi system with sphinx-build 1.2.3, the newest for that version. Do you know how I can update it to 1.6.5 without changing the base system?

**Comment by deoren** [comment] 2017-12-12 18:06
You can install a new version of sphinx via `python -m pip install sphinx --user`. I _think_ that the local version for that user takes precedence over the system version.

**Comment by rgerhards** [comment] 2017-12-14 18:18
It looks like the update solved the issue. At least I now get 52 search results. I close the issue. If this isn't solved, let us know and we'll re-open.

**Closed by rgerhards** 2017-12-14 18:18 UTC
Labels: bug, website
